# Generated by Django 4.2 on 2023-05-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=100)),
                ('receipe_desc', models.CharField(max_length=10000)),
                ('receipe_image', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
